# Features

sample: item # This is a comment

text_1: This is
  a short story
  about an apple.

text_2: |
  This is
  a short story
  about an apple.

text_3: >
  This is
  a short story
  about an apple.

text_4: >
  This is
  a short story

  about an apple.
