# Web server configuration

info:
  version: "1.0.0"
  website: "https://www.example.com"

database:
  type: sqlite
  path: /var/db/server.db

routes:
  - path: /api
    methods: [GET, POST]
  - path: /admin
    methods: [GET]
