!!src.model.config.config.Config
sqlite_config:
  !!src.model.config.sqlite_config.SqliteConfig
  buffer_db_path: C:\Users\aleksandr_petrovskii\AppData\Local\EPAM Connect\Db\buffer.db
  time_tracking_db_path: C:\Users\aleksandr_petrovskii\AppData\Local\EPAM Connect\Db\time_tracking.db
postgres_config:
  !!src.model.config.postgres_config.PostgresConfig
  server: stage-postgres-01.postgres.database.azure.com
  port: 5432
  database: cachedb_new
  username: readaccess@stage-postgres-01
  password: GOgZhU2HHrQvRMuSmTgo
timebase_config:
  !!src.model.config.timebase_config.TimebaseConfig
  server: timebase.stage.connect.epm-plx.projects.epam.com
  port: 8011
  username: admin
  password: Reifakeec5vuanaH
